"""Public API for the CrystalFlow deterministic expression engine."""

from .canonical import (
    canonical_hash,
    canonical_json,
    canonical_json_bytes,
    canonical_loads,
    canonical_sha256,
    canonicalize_json,
    content_hash,
)
from .engine import (
    DEFAULT_LIMITS,
    ENGINE_VERSION,
    IR_VERSION,
    Budget,
    CrystalFlowEngine,
    Engine,
    ResourceLimits,
    evaluate,
    execute,
    run,
    validate_expression,
    validate_program,
)
from .errors import (
    CanonicalizationError,
    CrystalFlowError,
    DSLValidationError,
    EvaluationError,
    InputValidationError,
    OutputValidationError,
    ResourceLimitError,
    SchemaDefinitionError,
)
from .schema import is_valid, validate_instance, validate_output, validate_schema

__all__ = [
    "Budget",
    "CanonicalizationError",
    "CrystalFlowEngine",
    "CrystalFlowError",
    "DEFAULT_LIMITS",
    "DSLValidationError",
    "ENGINE_VERSION",
    "Engine",
    "EvaluationError",
    "InputValidationError",
    "IR_VERSION",
    "OutputValidationError",
    "ResourceLimitError",
    "ResourceLimits",
    "SchemaDefinitionError",
    "canonical_hash",
    "canonical_json",
    "canonical_json_bytes",
    "canonical_loads",
    "canonical_sha256",
    "canonicalize_json",
    "content_hash",
    "evaluate",
    "execute",
    "is_valid",
    "run",
    "validate_expression",
    "validate_instance",
    "validate_output",
    "validate_program",
    "validate_schema",
]
